version: "3"

networks:
  sspanel:

volumes:
  mysql_data:

services:
  nginx:
    image: nginx
    restart: always
    container_name: nginx
    volumes:
      - ./configs/nginx/:/etc/nginx/conf.d
      - .:/usr/src/app
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - sspanel
  web:
    container_name: web
    restart: always
    image: ehco1996/django-sspanel:runtime
    environment:
      DJANGO_ENV: production
    volumes:
      - .:/usr/src/app
    networks:
      - sspanel
    ports:
      - 8080:8080
    working_dir: /usr/src/app
    command: uwsgi uwsgi.ini
  # 定时任务
  cron:
    container_name: cron
    restart: always
    image: ehco1996/django-sspanel:runtime
    environment:
      DJANGO_ENV: production
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
    networks:çç
      - sspanel
    working_dir: /usr/src/app
    command:
      [
        "/bin/sh",
        "-c",
        "crond && python manage.py crontab add && tail -f /var/log/django-cron.log",
      ]
